#!/bin/bash
set -eu
. /opt/config/.env
. /opt/shared/lib.sh

# ============================================================
# Issuance contracts: Deploy REO + IA + RAM + activation goals
# ============================================================
# Uses the deployment package's own Hardhat v3 + pnpm 10 toolchain.
# Runs after graph-contracts-horizon (Phases 1-3) has deployed the base protocol.
echo "==== Issuance contract deployment ===="

cd /opt/contracts/packages/deployment

# -- Fix pnpm node_modules when repo is bind-mounted (dev overlay) --
# pnpm's .pnpm store uses the install-time absolute path. When the repo is
# mounted from the host, the internal symlinks point at host paths that don't
# exist in the container. Detect and fix by re-running pnpm install.
if [ -d /opt/contracts/node_modules ] && \
   ! node -e "require('/opt/contracts/packages/deployment/node_modules/hardhat/package.json')" 2>/dev/null; then
  echo "  Dev overlay detected — running pnpm install to fix module resolution..."
  cd /opt/contracts && pnpm install --frozen-lockfile 2>&1 | tail -3
  cd /opt/contracts/packages/deployment
fi

# Symlink address books so Hardhat reads/writes land in /opt/config/
ln -sf /opt/config/horizon.json /opt/contracts/packages/horizon/addresses-local-network.json
ln -sf /opt/config/subgraph-service.json /opt/contracts/packages/subgraph-service/addresses-local-network.json
ln -sf /opt/config/issuance.json /opt/contracts/packages/issuance/addresses-local-network.json

# Ensure NetworkOperator in issuance address book (required by configure step)
TEMP_JSON=$(jq --arg op "${ACCOUNT0_ADDRESS}" \
  '.["1337"].NetworkOperator = {"address": $op}' /opt/config/issuance.json)
printf '%s\n' "$TEMP_JSON" > /opt/config/issuance.json

# -- Idempotency check --
# If all activation goals are complete, skip the whole deployment.
phase_skip=false
ram_address=$(jq -r '.["1337"].RecurringAgreementManager.address // empty' /opt/config/issuance.json 2>/dev/null || true)
ia_address=$(jq -r '.["1337"].IssuanceAllocator.address // empty' /opt/config/issuance.json 2>/dev/null || true)
reo_address=$(jq -r '.["1337"].RewardsEligibilityOracleA.address // empty' /opt/config/issuance.json 2>/dev/null || true)
if [ -n "$ram_address" ] && [ -n "$ia_address" ] && [ -n "$reo_address" ]; then
  ram_code=$(cast code --rpc-url="http://chain:${CHAIN_RPC_PORT}" "$ram_address" 2>/dev/null || echo "0x")
  ia_code=$(cast code --rpc-url="http://chain:${CHAIN_RPC_PORT}" "$ia_address" 2>/dev/null || echo "0x")
  reo_code=$(cast code --rpc-url="http://chain:${CHAIN_RPC_PORT}" "$reo_address" 2>/dev/null || echo "0x")
  if [ "$ram_code" != "0x" ] && [ "$ia_code" != "0x" ] && [ "$reo_code" != "0x" ]; then
    # Check if issuance is connected (IA is minter on GraphToken)
    graph_token=$(contract_addr L2GraphToken.address horizon)
    ia_is_minter=$(cast call --rpc-url="http://chain:${CHAIN_RPC_PORT}" \
      "${graph_token}" "isMinter(address)(bool)" "${ia_address}" 2>/dev/null || echo "false")
    if [ "$ia_is_minter" = "true" ]; then
      echo "Issuance contracts already deployed and activated"
      echo "  REO: $reo_address"
      echo "  IA:  $ia_address"
      echo "  RAM: $ram_address"
      phase_skip=true
    fi
  fi
fi

if [ "$phase_skip" = "false" ]; then
  # Clean stale deployment state from previous localNetwork runs (dev overlay)
  rm -rf /opt/contracts/packages/deployment/txs/localNetwork
  rm -rf /opt/contracts/packages/deployment/deployments/localNetwork

  # On localNetwork the governor key is available, so governance TXs
  # auto-execute via deploy:execute-governance.
  export GOVERNOR_KEY="${ACCOUNT1_SECRET}"

  # -- GIP-0088 Upgrade Phase --
  # Deploy, configure, transfer, upgrade — all scripts are idempotent.
  # Some steps generate governance TXs that need execution before proceeding.
  for step in \
    "GIP-0088:upgrade,deploy" \
    "GIP-0088:upgrade,configure" \
    "GIP-0088:upgrade,transfer" \
    "GIP-0088:upgrade,upgrade"; do
    echo "  --- Running: --tags ${step} ---"
    for attempt in 1 2 3; do
      if pnpm exec hardhat deploy --tags "${step}" --network localNetwork --skip-prompts; then
        break
      fi
      if ls /opt/contracts/packages/deployment/txs/localNetwork/*.json 2>/dev/null | grep -qv executed; then
        echo "  Executing pending governance TXs..."
        pnpm exec hardhat deploy:execute-governance --network localNetwork || true
      else
        echo "  Deploy step failed (no governance TXs pending)"
        exit 1
      fi
    done
    # Execute any governance TXs generated by this step
    if ls /opt/contracts/packages/deployment/txs/localNetwork/*.json 2>/dev/null | grep -qv executed; then
      echo "  Executing governance TXs..."
      pnpm exec hardhat deploy:execute-governance --network localNetwork || true
    fi
  done

  # -- GIP-0088 Activation Goals --
  # Each goal generates governance TXs independently; execute after each.
  for goal in \
    "GIP-0088:eligibility-integrate" \
    "GIP-0088:issuance-connect" \
    "GIP-0088:issuance-allocate"; do
    echo "  --- Running: --tags ${goal} ---"
    for attempt in 1 2 3; do
      if pnpm exec hardhat deploy --tags "${goal}" --network localNetwork --skip-prompts; then
        break
      fi
      if ls /opt/contracts/packages/deployment/txs/localNetwork/*.json 2>/dev/null | grep -qv executed; then
        echo "  Executing pending governance TXs..."
        pnpm exec hardhat deploy:execute-governance --network localNetwork || true
      else
        echo "  Activation goal failed (no governance TXs pending)"
        exit 1
      fi
    done
    if ls /opt/contracts/packages/deployment/txs/localNetwork/*.json 2>/dev/null | grep -qv executed; then
      echo "  Executing governance TXs..."
      pnpm exec hardhat deploy:execute-governance --network localNetwork || true
    fi
  done

  # Read deployed addresses
  reo_address=$(jq -r '.["1337"].RewardsEligibilityOracleA.address' /opt/config/issuance.json)
  ia_address=$(jq -r '.["1337"].IssuanceAllocator.address' /opt/config/issuance.json)
  ram_address=$(jq -r '.["1337"].RecurringAgreementManager.address' /opt/config/issuance.json)
fi

echo "  REO deployed at: ${reo_address:-<not deployed>}"
echo "  IA deployed at:  ${ia_address:-<not deployed>}"
echo "  RAM deployed at: ${ram_address:-<not deployed>}"

# -- REO local-network operator configuration --
# The GIP-0088 scripts handle deployment and role grants, but these operator
# actions are local-network-specific (short periods for fast iteration).
# Requires OPERATOR_ROLE (ACCOUNT0 gets this from the configure step).
if [ -n "${reo_address:-}" ]; then
  # Grant ORACLE_ROLE to the REO node signing key (ACCOUNT0).
  oracle_role=$(cast call --rpc-url="http://chain:${CHAIN_RPC_PORT}" \
    "${reo_address}" "ORACLE_ROLE()(bytes32)")
  has_role=$(cast call --rpc-url="http://chain:${CHAIN_RPC_PORT}" \
    "${reo_address}" "hasRole(bytes32,address)(bool)" "${oracle_role}" "${ACCOUNT0_ADDRESS}" 2>/dev/null || echo "false")
  if [ "$has_role" = "true" ]; then
    echo "  ORACLE_ROLE already granted to ${ACCOUNT0_ADDRESS}"
  else
    echo "  Granting ORACLE_ROLE to ${ACCOUNT0_ADDRESS} (via OPERATOR_ROLE)"
    cast send --rpc-url="http://chain:${CHAIN_RPC_PORT}" --confirmations=0 \
      --private-key="${ACCOUNT0_SECRET}" \
      "${reo_address}" "grantRole(bytes32,address)" "${oracle_role}" "${ACCOUNT0_ADDRESS}"
  fi

  # Enable eligibility validation (deny-by-default).
  validation_enabled=$(cast call --rpc-url="http://chain:${CHAIN_RPC_PORT}" \
    "${reo_address}" "getEligibilityValidation()(bool)" 2>/dev/null || echo "false")
  if [ "$validation_enabled" = "true" ]; then
    echo "  Eligibility validation already enabled"
  else
    echo "  Enabling eligibility validation (deny-by-default)"
    cast send --rpc-url="http://chain:${CHAIN_RPC_PORT}" --confirmations=0 \
      --private-key="${ACCOUNT0_SECRET}" \
      "${reo_address}" "setEligibilityValidation(bool)" true
  fi

  # Set eligibility period (short value for fast iteration).
  current_period=$(cast call --rpc-url="http://chain:${CHAIN_RPC_PORT}" \
    "${reo_address}" "getEligibilityPeriod()(uint256)" 2>/dev/null | awk '{print $1}')
  if [ "$current_period" = "${REO_ELIGIBILITY_PERIOD}" ]; then
    echo "  Eligibility period already set to ${REO_ELIGIBILITY_PERIOD}s"
  else
    echo "  Setting eligibility period to ${REO_ELIGIBILITY_PERIOD}s (was ${current_period}s)"
    cast send --rpc-url="http://chain:${CHAIN_RPC_PORT}" --confirmations=0 \
      --private-key="${ACCOUNT0_SECRET}" \
      "${reo_address}" "setEligibilityPeriod(uint256)" "${REO_ELIGIBILITY_PERIOD}"
  fi

  # Set oracle update timeout (long value to avoid accidental fail-safe).
  current_timeout=$(cast call --rpc-url="http://chain:${CHAIN_RPC_PORT}" \
    "${reo_address}" "getOracleUpdateTimeout()(uint256)" 2>/dev/null | awk '{print $1}')
  if [ "$current_timeout" = "${REO_ORACLE_UPDATE_TIMEOUT}" ]; then
    echo "  Oracle update timeout already set to ${REO_ORACLE_UPDATE_TIMEOUT}s"
  else
    echo "  Setting oracle update timeout to ${REO_ORACLE_UPDATE_TIMEOUT}s (was ${current_timeout}s)"
    cast send --rpc-url="http://chain:${CHAIN_RPC_PORT}" --confirmations=0 \
      --private-key="${ACCOUNT0_SECRET}" \
      "${reo_address}" "setOracleUpdateTimeout(uint256)" "${REO_ORACLE_UPDATE_TIMEOUT}"
  fi
fi

# Clean deployment metadata from address books.
for ab in horizon.json subgraph-service.json issuance.json; do
  if [ -f "/opt/config/$ab" ]; then
    TEMP_JSON=$(jq 'walk(if type == "object" then del(.implementationDeployment, .proxyDeployment) else . end)' "/opt/config/$ab")
    printf '%s\n' "$TEMP_JSON" > "/opt/config/$ab"
  fi
done

echo "==== Issuance deployment complete ===="
