chain: ./components/chain.sh
ipfs: ipfs daemon
contracts: sleep 5; ./components/contracts.sh

graph-node: sleep 5; ./components/graph-node.sh
network-subgraph: sleep 80; ./components/network-subgraph.sh

indexer-agent: sleep 90; ./components/indexer-agent.sh
indexer-service: sleep 120; ./components/indexer-service.sh
setup-indexer: sleep 135; ./commands/setup-indexer.sh

studio-api: sleep 90; ./components/studio-api.sh
gateway-agent: sleep 155; ./components/gateway-agent.sh
gateway: sleep 170; ./components/gateway.sh
# fisherman: ./components/fisherman.sh
# oracle: sleep 120; ./components/oracle.sh
# setup-query-user: sleep 180; ./commands/setup-query-user.sh
