networkIdentifier: "hardhat"
indexerOptions:
  geoCoordinates: [48.4682, -123.524]
  defaultAllocationAmount: 10000
  allocationManagementMode: "auto"
  restakeRewards: true
  poiDisputeMonitoring: false
  voucherRedemptionThreshold: 0.00001
  voucherRedemptionBatchThreshold: 10
  rebateClaimThreshold: 0.00001
  rebateClaimBatchThreshold: 10
subgraphs:
  maxBlockDistance: 5000
  freshnessSleepMilliseconds: 1000
