blockmeta_auth_token = ""
owner_address = "$BLOCK_ORACLE_OWNER_ADDRESS"
owner_private_key = "$BLOCK_ORACLE_OWNER_SECRET_KEY"
data_edge_address = "$DATA_EDGE_CONTRACT_ADDRESS"
epoch_manager_address = "$EPOCH_MANAGER_CONTRACT_ADDRESS"
subgraph_url = "$SUBGRAPH_URL"
bearer_token = "TODO"
log_level = "trace"

[protocol_chain]
name = "eip155:1337"
jrpc = "$PROTOCOL_CHAIN_JRPC_URL"
polling_interval_in_seconds = 20

[indexed_chains]
"eip155:1337" = "$PROTOCOL_CHAIN_JRPC_URL"
